<?php

/**
 * @author simon <crcms@crcms.cn>
 * @datetime 2018-04-29 20:30
 * @link http://crcms.cn/
 * @copyright Copyright &copy; 2018 Rights Reserved CRCMS
 */

namespace CrCms\Document\Repositories;

use CrCms\Document\Models\DocumentModel;
use CrCms\Document\Models\Model;
use CrCms\Foundation\App\Repositories\AbstractRepository;

/**
 * Class DocumentRepository
 * @package CrCms\Document\Repositories
 */
class DocumentRepository extends AbstractRepository
{
    protected $documentModel;

    public function __construct(Model $model)
    {
        $this->documentModel = $model;
        parent::__construct();
    }

    public function newModel(): DocumentModel
    {
//        dump($this->documentModel->table_name);
        return app(DocumentModel::class);//->setTable($this->documentModel->table_name);//->setCollection($this->documentModel->table_name);
    }

    public function create(array $data)
    {
        $this->setGuard(array_keys($data));
        return parent::create($data); // TODO: Change the autogenerated stub
    }

}